name: "Terraform Infrastructure Validation"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Lint and Validate"
    runs-on: ubuntu-latest

    # Definimos el directorio de trabajo donde están tus módulos
    defaults:
      run:
        working-directory: ./modules/compute/virtual-machine

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Ejecuta el formato en todo el repo y arregla el error code 3
      - name: Terraform Format
        run: terraform fmt -check -recursive .

      # Valida cada blueprint por separado (puedes añadir más líneas aquí)
      - name: Validate Lab 01
        run: |
          cd blueprints/compute-basics
          terraform init -backend=false
          terraform validate