name: "Terraform Infrastructure Validation"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Lint and Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Verifica el formato en todo el repositorio
      - name: Terraform Format Check
        run: terraform fmt -check -recursive .

      # Validaci√≥n del Lab 01
      - name: Validate Lab 01
        run: |
          if [ -d "blueprints/compute-basics" ]; then
            cd blueprints/compute-basics
            terraform init -backend=false
            terraform validate
          else
            echo "Directory blueprints/compute-basics not found"
            exit 1
          fi